### ISSUE TITLE
Timed out after latest Sonos update with TruePlay

### ISSUE THREAD

**Issue by jeffryvu** [soffes/sonos#51]
I just updated my Sonos system to the latest version with support for TruePlay on November 10, 2015.

Since that update I can no longer connect to Sonos, instead I get a "Timed out..." message.

Does anyone have the same experience?

I'm trying using irb:
require 'rubygems'
require 'sonos'
system = Sonos::System.new # Auto-discovers your system
speaker = system.speakers.first

**Comment by jeffryvu** [comment]
Ok, I now see that this is the exact same issue as #23. I am on Ruby 2.0 BTW.

**Comment by masone** [comment]
I am successfully running this gem against a Sonos with the TruePlay update installed (but not enabled) on Ruby 2.0.

**Comment by jeffryvu** [comment]
Yes, this doesn't seem to be related to the TruePlay update. I'll close this issue.
